// Copyright 2021 THL A29 Limited, a Tencent company.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	carrierv1alpha1 "github.com/ocgi/carrier/pkg/apis/carrier/v1alpha1"
	versioned "github.com/ocgi/carrier/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ocgi/carrier/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ocgi/carrier/pkg/client/listers/carrier/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SquadInformer provides access to a shared informer and lister for
// Squads.
type SquadInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SquadLister
}

type squadInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSquadInformer constructs a new informer for Squad type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSquadInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSquadInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSquadInformer constructs a new informer for Squad type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSquadInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CarrierV1alpha1().Squads(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CarrierV1alpha1().Squads(namespace).Watch(options)
			},
		},
		&carrierv1alpha1.Squad{},
		resyncPeriod,
		indexers,
	)
}

func (f *squadInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSquadInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *squadInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&carrierv1alpha1.Squad{}, f.defaultInformer)
}

func (f *squadInformer) Lister() v1alpha1.SquadLister {
	return v1alpha1.NewSquadLister(f.Informer().GetIndexer())
}
